on:
  workflow_call:

jobs:
  artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Zip up docs
        run: |
          set -vxeuo pipefail
          if [ -d html ]; then
            mv html $GITHUB_REF_NAME
            zip -r docs.zip $GITHUB_REF_NAME
            rm -rf $GITHUB_REF_NAME
          fi

      - name: Create GitHub Release
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          prerelease: ${{ contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc') }}
          files: "*"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
