name: Periodic

on:
  workflow_dispatch:
  schedule:
    # Run weekly to check URL links still resolve
    - cron: "0 8 * * WED"

jobs:
  linkcheck:
    uses: ./.github/workflows/_tox.yml
    with:
      tox: docs build -- -b linkcheck
